# Generated by Django 4.2.2 on 2023-07-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_product_category_remove_product_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='menuitem',
            field=models.ManyToManyField(to='home.menuitems'),
        ),
    ]
