# Generated by Django 4.2.2 on 2023-07-04 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_product_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.product')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('home.product',),
        ),
    ]
