# Generated by Django 4.2.2 on 2023-07-04 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_variableproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariableProduct',
        ),
    ]
