# Generated by Django 4.2.2 on 2023-07-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_product_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='Flavor',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
