# Generated by Django 4.2.2 on 2023-07-06 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_productvariant_flavor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
    ]
