# Generated by Django 4.2.2 on 2023-07-06 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_productvariant_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
    ]
