# Generated by Django 4.2.2 on 2023-07-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_subcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='category', to='home.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subCategory',
            field=models.ManyToManyField(related_name='sub', to='home.subcategory'),
        ),
    ]
