# Generated by Django 4.1.7 on 2023-08-17 20:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_description_product_benefits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ideal_for',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
