# Generated by Django 4.1.7 on 2023-07-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_customer_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
